version: '3.8'

services:
  # 🕌 MuslimHub Backend API
  backend:
    build:
      context: .
      target: backend-build
    container_name: muslimhub-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/muslimhub
      - JWT_SECRET=${JWT_SECRET:-your_super_secret_jwt_key}
      - JWT_EXPIRE=30d
    depends_on:
      - mongodb
      - redis
    networks:
      - muslimhub-network
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"\]
      interval: 30s
      timeout: 10s
      retries: 3

  # 🎨 MuslimHub Frontend
  frontend:
    build:
      context: .
      target: frontend-build
    container_name: muslimhub-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - REACT_APP_ENVIRONMENT=production
    depends_on:
      - backend
    networks:
      - muslimhub-network
    restart: unless-stopped

  # 🍃 MongoDB Database
  mongodb:
    image: mongo:6-jammy
    container_name: muslimhub-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD:-password123}
      - MONGO_INITDB_DATABASE=muslimhub
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - muslimhub-network
    restart: unless-stopped

  # 🚀 Redis Cache
  redis:
    image: redis:7-alpine
    container_name: muslimhub-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - muslimhub-network
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru

  # 📊 Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: muslimhub-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - muslimhub-network
    restart: unless-stopped

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  muslimhub-network:
    driver: bridge

# 🤲 Bismillah - In the name of Allah, we begin this revolutionary journey
